.MODEL SMALL
.STACK 100H
.DATA
;THE VARIABLE WHICH ARE DECLARED
    ;BH BL 8 BITS REGISTER 1 BYTE
    ;BX 16 BITS REGISTER 1 WORD
    
    NUM DB 'd' ; d = 100
    NUM2 DB ?
    CHAR DB '#'
    STR DB "MY NAME IS EMU8086"
    CHAR2 DB ?
    
    
.CODE
;CODE SEGMENT
MAIN PROC ; INT MAIN
    ;CODE STATEMENT
    MOV AX , @DATA
    MOV DS , AX
     
    MOV AH , 4CH 
    INT 21H
    MAIN ENDP
END MAIN ; RETURN 0
    
    
    